apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: microservices
type: Opaque
stringData:
  DB_URL: jdbc:mysql://eks-microservices-mysql.xxxx.us-east-1.rds.amazonaws.com:3306/productsdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  DB_USERNAME: admin
  DB_PASSWORD: your-secure-password
